sudo: false
language: node_js
node_js:
  - 'node'
  - '7.7.3'
env:
  - EXTENSION_ID=lmjdlojahmbbcodnpecnjnmlddbkjhnn
deploy:
  provider: script
  script: npm run release
  on:
    branch: master
    tags: true
